config/routes.rb
EpicImages::Application.routes.draw do
  root to: 'home#index'

  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  resources :sessions, only: :create

  get '/about_us', to: 'home#about_us'
  get '/contact_us', to: 'home#contact_us'
  resources :blogs, only: [:index, :show]
  resources :tags, path: 'gallery', only: [:index, :show]
  get 'photos/search' => 'tags#search', as: :photos_search

  namespace :admin do
    resource :users, only: [:edit, :update]
    resources :photos, except: [:new, :show] do
      collection do
        put :update_all
        get :all_photos
      end
      member do
        get :image
      end
    end
    resources :blogs
    resources :tags, path: 'galleries', only: [:show, :create] do
      get :photos, on: :member
    end
    root :to => 'admin#index'
  end

end

app/views/layouts/admin/_menu.html.haml
%header
  %nav.menu
    = link_to admin_root_path, class: 'clearfix' do
      .adminLogo.left
    .right
      .relative.right
        = link_to '#', class: 'profile dropdown-toggle', 'data-toggle' => 'dropdown' do
          = current_user
          %b.caret
        %ul.dropdown-menu
          %li
            = link_to edit_admin_users_path do
              %span.icon16.man
              Edit profile
          %li.divider
          %li
            = link_to logout_path do
              %span.glyph.exit
              Logout
      %ul
        %li= link_to 'HOME', admin_root_path, class: current_page_class(admin_root_path)
        %li= link_to 'PHOTOS', admin_photos_path, class: current_page_class(admin_photos_path)
        %li= link_to 'BLOGS', admin_blogs_path, class: current_page_class(admin_blogs_path)