config/routes.rb
EpicImages::Application.routes.draw do
  root to: 'home#index'

  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  resources :sessions, only: :create

  get '/about_us', to: 'home#about_us'
  get '/contact_us', to: 'home#contact_us'
  resources :blogs, only: [:index, :show]
  resources :tags, path: 'gallery', only: [:index, :show]
  get 'photos/search' => 'tags#search', as: :photos_search

  namespace :admin do
    resource :users, only: [:edit, :update]
    resources :photos, except: [:new, :show] do
      collection do
        put :update_all
        get :all_photos
      end
      member do
        get :image
      end
    end
    resources :blogs
    resources :tags, path: 'galleries', only: [:show, :create] do
      get :photos, on: :member
    end
    root :to => 'admin#index'
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @photos = Photo.featured
    @blog = Blog.most_recent
  end
end

app/views/home/about_us.html.haml
%section
  = image_tag 'david_and_angie.jpg', alt: 'About Us', class: 'aboutUs'

  %p
    angela and i are a husband/wife team and we love taking epic pictures! i generally shoot most of the images while angie keeps everyone organized and laughing! we have complimenting personalities which usually makes our clients feel comfortable with our professionalism, yet at ease by our lighthearted nature. we are always early and on point, yet flexible and understanding. we are very relaxed and we rarely “pose” you. your pictures will be candid, creative and journalistic in nature; capturing true emotion, expressions, and events.

    we offer complimentary engagement shoots when you book your wedding photography with us. when you book a wedding with us, we offer a complimentary engagement shoot. so we feel as though we are your friends and guests on your special day. we believe that your photographs should not only be epic, but also artistic. art pieces that you can be proud of and even build your interior design from. your wedding plans are expensive from start to finish; your photographs should be as breathtaking as you are on that day.

    we recently opened epic studios, we are excited about our new and different take on studio photography!

    the greatest compliment a client can give is repeat business, and the second best is to refer a friend. most of our advertising is “word-of-mouth,” and we have enjoyed many repeat clients and kind referrals.

    we look forward to speaking with you soon!

    david and angie

app/views/home/contact_us.html.haml
%h1 Contact form

app/views/home/index.html.haml
%section
  #photoCarousel.carousel.slide
    - unless @photos.empty?
      .carousel-inner
        - @photos.each_with_index do |photo, index|
          .item{ class: index.eql?(0) ? 'active' : '' }
            = image_tag photo.image.url(:cropped), alt: photo.caption

      = link_to '&lsaquo;'.html_safe, '#photoCarousel', class: 'carousel-control left', 'data-slide' => 'prev'
      = link_to '&rsaquo;'.html_safe, '#photoCarousel', class: 'carousel-control right', 'data-slide' => 'next'

  .grid.clearfix
    = link_to tags_path, class: 'item' do
      = image_tag 'galleries.jpg'
      .itemTitle Gallery
    = link_to '#', class: 'item' do
      = image_tag 'testimonials.jpg'
      .itemTitle Specials
    = link_to '#', class: 'item' do
      = image_tag 'services.jpg'
      .itemTitle Benefits
    = link_to about_us_path, class: 'item' do
      = image_tag 'about.jpg'
      .itemTitle About Us

/ %section.attention
/   SCHEDULE YOUR SHOOT TODAY

%section
  %h2.sectionTitle Featured Special
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mollis pellentesque auctor. Etiam elit ipsum,
  semper non scelerisque ac, imperdiet ut justo. Nunc molestie, mauris sed tristique aliquam, enim nisl sollicitudin
  libero, quis elementum arcu tellus non mi. Morbi interdum interdum risus id lacinia. Pellentesque vel lectus metus.
  Sed mi odio, tincidunt eu mollis nec, pulvinar eu nulla. Ut gravida ipsum vel dui elementum bibendum. Aliquam erat
  volutpat. Nam malesuada, elit sed molestie venenatis, dui arcu mattis odio, non pharetra sem lectus sit amet arcu.
  Phasellus eget congue augue. Ut est augue, venenatis eget scelerisque quis, gravida vel odio. Curabitur euismod dui
  eget leo vestibulum feugiat. Integer tempus, urna vel ornare tristique, lorem velit euismod leo, vel posuere ligula
  ante in risus. Cras euismod est ac nulla molestie et venenatis nibh dapibus. Pellentesque congue varius mauris, a
  pulvinar neque facilisis in.
  Donec ac leo urna.

- if @blog
  %section.blogs
    %h2.sectionTitle= link_to 'BLOG &rarr;'.html_safe, blogs_path
    %h3= link_to @blog.title, blog_path(@blog)
    %p
      = truncate(@blog.body, length: 385)
      - if @blog.body.length > 385
        %strong= link_to 'Continue Reading &Rarr;'.html_safe, blog_path(@blog)