config/routes.rb
EpicImages::Application.routes.draw do
  root to: 'home#index'

  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  resources :sessions, only: :create

  get '/about_us', to: 'home#about_us'
  get '/contact_us', to: 'home#contact_us'
  resources :blogs, only: [:index, :show]
  resources :tags, path: 'gallery', only: [:index, :show]
  get 'photos/search' => 'tags#search', as: :photos_search

  namespace :admin do
    resource :users, only: [:edit, :update]
    resources :photos, except: [:new, :show] do
      collection do
        put :update_all
        get :all_photos
      end
      member do
        get :image
      end
    end
    resources :blogs
    resources :tags, path: 'galleries', only: [:show, :create] do
      get :photos, on: :member
    end
    root :to => 'admin#index'
  end

end

app/models/blog.rb
class Blog < ActiveRecord::Base

  attr_accessible :title, :body

  validates :title, :body, presence: true
  validates :title, uniqueness: true

  TRUNCATE_LENGTH = 1000

  def self.order_most_recent
    order('created_at desc')
  end

  def self.most_recent
    order_most_recent.first
  end

  def to_param
    "#{id}-#{title.parameterize}"
  end
end

app/controllers/admin/blogs_controller.rb
class Admin::BlogsController < Admin::AdminController
  before_filter :load_blog, only: [:edit, :update, :destroy]

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new params[:blog]

    if @blog.save
      flash[:success] = 'You have successfully created a new blog'
      redirect_to admin_blogs_path
    else
      flash[:error] = @blog.errors.full_messages.join('<br/>')
      render :new
    end
  end

  def update
    if @blog.update_attributes(params[:blog])
      flash[:success] = 'You have successfully updated the blog'
      redirect_to admin_blogs_path
    else
      flash[:error] = @blog.errors.full_messages.join('<br/>')
      render :edit
    end
  end

  def destroy
    if @blog.destroy
      flash[:success] = 'You have successfully deleted the blog'
    else
      flash[:error] = 'Could not delete the blog. Please try again'
    end
    redirect_to admin_blogs_path
  end

  private

    def load_blog
      @blog = Blog.find params[:id]
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.order_most_recent
  end

  def show
    @blog = Blog.find(params[:id])
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper

  def read_more_link(blog)
    link_to 'READ MORE &rarr;'.html_safe, blog_path(blog) if blog.body.length > Blog::TRUNCATE_LENGTH
  end
end

app/views/admin/blogs/_blog.html.haml
.blog
  = link_to blog.title, edit_admin_blog_path(blog)
  %span.time= format_time blog.created_at
  .actions.right
    = link_to edit_admin_blog_path(blog) do
      %span.icon24.edit
    = link_to admin_blog_path(blog), method: :delete, 'data-confirm' => 'Are you sure you want to delete this blog?'do
      %span.glyph.trash.red.large

app/views/admin/blogs/_form.html.haml
= form_for [:admin, @blog] do |f|
  = render 'layouts/flash', flash: flash
  .input
    %label Title
    = f.text_field :title
  .input
    %label Description
    = f.text_area :body
  .submit
    = save_button
    = link_to_cancel admin_blogs_path

app/views/admin/blogs/edit.html.haml
%section
  %h2.sectionTitle
    %span.icon24.edit
    Edit blog
  = link_to admin_blog_path(@blog), method: :delete, class: 'delete' do
    %span.glyph.trash.red.large
  = render 'form'

app/views/admin/blogs/index.html.haml
= link_to new_admin_blog_path, class: 'button' do
  %span.icon16.plus
  Write new blog

%section
  %h2.sectionTitle Blogs
  = render @blogs

app/views/admin/blogs/new.html.haml
%section
  %h2.sectionTitle
    %span.icon24.plus
    Write a new blog
  = render 'form'