config/routes.rb
EpicImages::Application.routes.draw do
  root to: 'home#index'

  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  resources :sessions, only: :create

  get '/about_us', to: 'home#about_us'
  get '/contact_us', to: 'home#contact_us'
  resources :blogs, only: [:index, :show]
  resources :tags, path: 'gallery', only: [:index, :show]
  get 'photos/search' => 'tags#search', as: :photos_search

  namespace :admin do
    resource :users, only: [:edit, :update]
    resources :photos, except: [:new, :show] do
      collection do
        put :update_all
        get :all_photos
      end
      member do
        get :image
      end
    end
    resources :blogs
    resources :tags, path: 'galleries', only: [:show, :create] do
      get :photos, on: :member
    end
    root :to => 'admin#index'
  end

end

app/views/layouts/_flash.html.haml
- flash.each do |key, msg|
  %div{ class: "alert alert-#{key}" }
    %button.close{ 'data-dismiss' => 'alert' } &times;
    = msg.html_safe

app/views/layouts/_header.html.haml
%header
  %nav.menu.clearfix
    = link_to root_path, class: 'clearfix' do
      .logo.left
    %ul.right
      %li= link_to 'HOME', root_path, class: current_page_class(root_path)
      %li= link_to 'ABOUT US', about_us_path, class: current_page_class(about_us_path)
      %li= link_to 'GALLERY', tags_path, class: current_page_class(tags_path)
      %li= link_to 'BLOG', blogs_path, class: current_page_class(blogs_path)
      %li= link_to 'CONTACT', contact_us_path, class: current_page_class(contact_us_path)

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title EpicImages
    = stylesheet_link_tag    "admin", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = render 'layouts/admin/menu'
    .content{ 'ng-app' => content_for?(:angular_app) ? yield(:angular_app) : nil, 'ng-controller' => content_for?(:angular_controller) ? yield(:angular_controller) : nil }
      = yield
      %footer
        .copyright &copy; COPYRIGHT 2013 EPIC IMAGES

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title EpicImages
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .content
      = render 'layouts/header'
      .container{ 'ng-app' => content_for?(:angular_app) ? yield(:angular_app) : nil, 'ng-controller' => content_for?(:angular_controller) ? yield(:angular_controller) : nil }
        = yield
        %footer
          .copyright &copy; COPYRIGHT 2013 EPIC IMAGES